import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/providers/ToastProvider";
import NextAuthProvider from "@/providers/NextAuthProvider";
import Navbar from "@/components/ui/Navbar";
import Sidebar from "@/components/ui/Sidebar";
import { getServerSession } from "next-auth";
import { authOptions } from "@/libs/AuthOption";
import LoggedInLayout from "@/components/Layout/LoggedInLayout";
import LoggedOutLayout from "@/components/Layout/LoggedOutLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    
    const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
      <ToastProvider />
      <NextAuthProvider>
      {session ? (
          <LoggedInLayout>{children}</LoggedInLayout>
        ) : (
          <LoggedOutLayout>{children}</LoggedOutLayout>
        )}

        </NextAuthProvider>
      </body>
    </html>
  );
}
