import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/providers/ToastProvider";
import NextAuthProvider from "@/providers/NextAuthProvider";
import Navbar from "@/components/ui/Navbar";
import Sidebar from "@/components/ui/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ToastProvider />
      <NextAuthProvider>
      <div className="min-h-screen flex">
      {/* Sidebar */}
        <Sidebar />
        <div className="flex-1 flex flex-col">
        {/* Navbar */}
        <div className="md:pl-64">
                <Navbar />
            </div>
        {/* Dashboard content */}
          <div className="pt-16 md:pl-72 p-4 flex-grow bg-slate-200">
            {children}
          </div>
        </div>
      </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
